### ISSUE TITLE
What happened with the device object?

### ISSUE THREAD

**Issue by danielkilbo** [sics-iot/lwm2m-contiki#5]
What happened with the macros that defined the device object in lwm22-object.h?
LWM2M_RESOURCES
LWM2M_RESOURCE_STRING
...

The structure made it possible to give the resources a separate resource id. But now when the macros are removed I cannot se how the resources are identified any more.

**Comment by danielkilbo** [comment]
Found it now, that the id:s are listed in the resources[] and looked up in the callback.
Need to rewrite our device object.
Sorry no issue, just got confused by the change.

**Comment by joakimeriksson** [comment]
Sorry - the change is yet a bit undocumented but I hope to give a more official release soon including documentation. By then I will also have all relevant IPSO objects ported to the new implementation. Thanks for testing and giving feedback.
