### ISSUE TITLE
The server object uses faulty type when allocated.

### ISSUE THREAD

**Issue by danielkilbo** [sics-iot/lwm2m-contiki#6]
In the lwm2m_server.c file the server object is allocated using the lwm2m_object_instance_t type which would be nice if it is not casted to the type server_value_t in the lwm2m_callback().
The server_value_t type is larger and contains two more elements server_id and lifetime. These elements are now read from the memory position directly after the server object.
When the server_value_t is used to allocate the server object the lifetime could be set to a default value.

The same problem exist for the sequrity object as well.

Also noted that lwm2m_server_init() and lwm2m_security_init() are never called. Removed by comment in lwm2m_enginge.c. The result is that the linker will not add that code...

Please guide me here!

**Comment by joakimeriksson** [comment]
This is a fake version of C++ and Java "inheritance" in a sense. The objects / structs are extended versions of the lwm2m_object_instance_t type - e.g. they have additional data in them.
