### ISSUE TITLE
lwm2m_rd_client_set_lifetime() strange logic

### ISSUE THREAD

**Issue by danielkilbo** [sics-iot/lwm2m-contiki#7]
`void
lwm2m_rd_client_set_lifetime(uint16_t lifetime)
{
  session_info.lifetime = (0 <= lifetime) ? lifetime : LWM2M_DEFAULT_CLIENT_LIFETIME;
}`
The function above in lwm2m-rd-client seams to use strange logic.

- lifetime cannot be less than zero (unsigned)
- Why use it the value in lifetime if it is zero?
- If not zero the default value is used...

**Comment by joakimeriksson** [comment]
Thanks for reporting. This has been fixed to a more easy to understand code now.
```
  if(lifetime > 0) {
    session_info.lifetime = lifetime;
  } else {
    session_info.lifetime = LWM2M_DEFAULT_CLIENT_LIFETIME;
  }
```
